### ISSUE TITLE
Formula1_setup.bash missing files

### ISSUE THREAD

**Issue by dcharrezt** [RoboticsLabURJC/2019-tfm-ignacio-arranz#9]
Hi, 

I was following this [instructions](https://roboticslaburjc.github.io/2019-tfm-ignacio-arranz/install/), and running the `bash formula1_setup.bash` says that there are some missing files.

`cp: cannot stat '../assets/urdf/kobuki_urdf/urdf/': No such file or directory`
`cp: cannot stat '../assets/meshes/lidar_lite_v2_withRay.dae': No such file or directory`

**Comment by igarag** [comment]
Hhello @dcharrezt.

I guess you figured it out (sorry for the delay), from what I saw on your blog. Those files can be found at [this link](https://github.com/RoboticsLabURJC/2019-tfm-ignacio-arranz/tree/master/gym-gazebo/gym_gazebo/envs/assets/urdf/kobuki_urdf/urdf)

With these iterations, small installation errors will be fixed. Thanks for the report.

**Comment by dcharrezt** [comment]
Hello @igarag,

Thanks for replying, I'm happy to help!, I am closing this issue since those files were added to the repository.
